name: Database

on:
    push:
    pull_request:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test-build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          
          - name: Login to GitHub Container Registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build Docker Image
            working-directory: . 
            run: |
              docker build . --tag ghcr.io/cmlai-lab/dcsd:latest
              docker push ghcr.io/cmlai-lab/dcsd:latest
